---
AWSTemplateFormatVersion: "2010-09-09"
Description: "PS CodeBuild Stack: <%=$PLASTER_PARAM_ModuleName%>"

Parameters:
  ProjectName:
    Description: name of PS Module. Used as project tag value for all resources.
    Type: String
    Default: <%=$PLASTER_PARAM_ModuleName%>

  ProjectDescription:
    Description: short description of your PS module project.
    Type: String

  RepositoryUrl:
    Description: "HTTPS Clone URL of the repository in GitHub. Example: 'https://github.com/owner/repo.git'"
    Type: String

  #BranchName:
  #  Default: master
  #  Description: the GitHub branch that will be monitored for builds (CASE SENSITIVE).
  #  Type: String

  CodeBuildBadgeEnabled:
    Type: String
    Default: "true"
    Description: Selects whether to enable CodeBuild Build Badges.
    AllowedValues:
      - "true"
      - "false"

  CodeBuildTimeoutInMinutes:
    Type: Number
    Default: 30
    Description: The number of minutes before a CodeBuild build will timeout.

  # https://docs.aws.amazon.com/codebuild/latest/userguide/create-project.html#create-project-cli
  #CodeBuildEnvironment:
  #  Type: String
  #  Default: WINDOWS_CONTAINER
  #  Description: The type of build environment.
  #  AllowedValues:
  #    - WINDOWS_CONTAINER
  #    - LINUX_CONTAINER

  # https://docs.aws.amazon.com/codebuild/latest/userguide/create-project.html#create-project-cli
  #CodeBuildComputeType:
  #  Type: String
  #  Default: BUILD_GENERAL1_MEDIUM
  #  Description: The size of the CodeBuild instance. (Windows Containers do NOT support small)
  #  AllowedValues:
  #    - BUILD_GENERAL1_SMALL
  #    - BUILD_GENERAL1_MEDIUM
  #    - BUILD_GENERAL1_LARGE

  # https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
  #CodeBuildImage:
  #  Type: String
  #  Default : aws/codebuild/windows-base:1.0
  #  Description: The size of the CodeBuild instance. (Windows Containers do NOT support small)
  #  AllowedValues:
  #    - aws/codebuild/windows-base:1.0
  #    - aws/codebuild/dot-net:core-2.1

  BuildSpecFile:
    Type: String
    Default: buildspec_powershell_windows.yml
    Description: The build file to be run by CodeBuild.
    AllowedValues:
      - buildspec_powershell_windows.yml
      - buildspec_pwsh_windows.yml
      - buildspec_pwsh_linux.yml

  DeployEmailNotifications:
    Type: String
    Default: "no"
    Description: "CodeBuild will send email notifications of state changes."
    AllowedValues:
      - "yes"
      - "no"

  EmailForNotifications:
    Type: String
    Default: ignored@doesnotexist.com
    Description: Email Address for SNS Notifications
    AllowedPattern: "^[\\x20-\\x45]?[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project and Tagging
        Parameters:
          - ProjectName
          - ProjectDescription
      - Label:
          default: Specify GitHub Repository and Branch
        Parameters:
          - RepositoryUrl
          #- BranchName
      - Label:
          default: CodeBuild
        Parameters:
          - CodeBuildBadgeEnabled
          - CodeBuildTimeoutInMinutes
          #- CodeBuildEnvironment
          #- CodeBuildComputeType
          - BuildSpecFile
      - Label:
          default: Email Notifications
        Parameters:
          - DeployEmailNotifications
          - EmailForNotifications
    ParameterLabels:
      ProjectName:
        default: Module Name
      ProjectDescription:
        default: Module Description
      RepositoryUrl:
        default: GitHub Repository URL
      #BranchName:
      #  default: Branch Name
      CodeBuildBadgeEnabled:
        default: Badge Enabled
      CodeBuildTimeoutInMinutes:
        default: Timeout in Minutes
      #CodeBuildEnvironment:
      #  default: Container Type
      #CodeBuildComputeType:
      #  default: Container Size
      BuildSpecFile:
        default: Buildspec file
      DeployEmailNotifications:
        default: Deploy Email Notifications
      EmailForNotifications:
        default: Email Address

#Mappings:

Conditions:
  DeployEmailNotificationsCondition:
    !Equals [!Ref DeployEmailNotifications, "yes"]
  PSWindows: !Equals [!Ref BuildSpecFile, "buildspec_powershell_windows.yml"]
  PWSHWindows: !Equals [!Ref BuildSpecFile, "buildspec_pwsh_windows.yml"]
  WindowsImage:
    Fn::Or:
    - Condition: PSWindows
    - Condition: PWSHWindows
  #LinuxImage: !Equals [!Ref BuildSpecFile, "buildspec_pwsh_linux.yml"]
  #WindowsImage: !Equals [!Ref CodeBuildEnvironment, "WINDOWS_CONTAINER"]

Resources:
  # The IAM Role CodeBuild will run the container as
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CBCloudWatchPublishing
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/<%=$PLASTER_PARAM_ModuleName%>"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/<%=$PLASTER_PARAM_ModuleName%>:*"
        - PolicyName: CBS3ArtifactAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - arn:aws:s3:::codepipeline-${AWS::Region}-*

  # The CodeBuild Project configuration
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: !Ref CodeBuildBadgeEnabled
      Description: !Ref ProjectDescription
      Environment:
        #ComputeType: !Ref CodeBuildComputeType
        ComputeType:
          !If
          - WindowsImage
          - BUILD_GENERAL1_MEDIUM
          - BUILD_GENERAL1_SMALL
        Image:
          !If [
            WindowsImage,
            "aws/codebuild/windows-base:1.0",
            "aws/codebuild/dot-net:core-2.1",
          ]
        #Type: !Ref CodeBuildEnvironment
        Type:
          !If
          - WindowsImage
          - WINDOWS_CONTAINER
          - LINUX_CONTAINER
      Name: !Join
        - "-"
        - - !Ref ProjectName
          - !Select [0, !Split [".", !Ref BuildSpecFile]]
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: GITHUB
        Auth:
          Type: OAUTH
        Location: !Ref RepositoryUrl
        BuildSpec: !Ref BuildSpecFile
      Tags:
        - Key: Service
          Value: !Ref ProjectName
      TimeoutInMinutes: !Ref CodeBuildTimeoutInMinutes
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
          - - Type: BASE_REF
              Pattern: ^refs/heads/master$
            - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
  #https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-webhookfilter.html

  # An SNS Topic used for CodeBuild status updates
  SNSTopicForCodeBuildUpdates:
    Type: AWS::SNS::Topic

  # The SNS Topic Policy
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: SNSTopicPolicy
        Version: "2012-10-17"
        Statement:
          - Sid: AllowEvents
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SNSTopicForCodeBuildUpdates
      Topics:
        - !Ref SNSTopicForCodeBuildUpdates

  # The SNS Email Subscription
  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: DeployEmailNotificationsCondition
    Properties:
      Endpoint: !Ref EmailForNotifications
      Protocol: email
      TopicArn: !Ref SNSTopicForCodeBuildUpdates

  # The CodeBuild event for status updates
  CodeBuildEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger notifications based on CodeBuild state changes
      EventPattern:
        source:
          - aws.codebuild
        detail-type:
          - CodeBuild Build State Change
        detail:
          build-status:
            - IN_PROGRESS
            - SUCCEEDED
            - FAILED
            - STOPPED
          project-name:
            - !Ref CodeBuildProject
      State: ENABLED
      Targets:
        - Arn: !Ref SNSTopicForCodeBuildUpdates
          Id: !Sub "${AWS::StackName}"
          InputTransformer:
            InputTemplate: '"The PowerShell solution build for <projectname> is in state <status> at <at>."'
            InputPathsMap:
              projectname: "$.detail.project-name"
              status: "$.detail.build-status"
              at: "$.time"
              account: "$.account"

Outputs:
  CodeBuildProject:
    Description: The name of the CodeBuild Project.
    Value: !Ref CodeBuildProject

  SNSTopic:
    Description: The SNS Topic used for CodeBuild status updates
    Value: !Ref SNSTopicForCodeBuildUpdates

  CodeBuildURL:
    Description: CodeBuild URL
    Value:
      Fn::Join:
        - ""
        - - https://console.aws.amazon.com/codebuild/home?region=
          - Ref: AWS::Region
          - "#/projects/"
          - Ref: CodeBuildProject
          - "/view"
